name: ground_control_client
version: 0.21.1
description: A client library for the Serverpod Ground Control API. Used to manage Serverpod Cloud projects.
repository: https://github.com/serverpod/serverpod_cloud_clients
homepage: https://serverpod.dev
issue_tracker: https://github.com/serverpod/serverpod_cloud_clients/issues

topics:
  - api
  - client

environment:
  # Note, this range must include all the supported customer Dart SDK versions.
  sdk: ">=3.8.0 <4.0.0"


dependencies:
  serverpod_client: 3.1.1
  serverpod_auth_idp_client: 3.1.1

  http: ^1.0.0
  mocktail: ^1.0.4
  dio: ^5.8.0+1
